### ISSUE TITLE
Error while closing (via Tray icon -> Exit)

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#136]
Registering it so it will not be forgotten.

    ---------------------------
    Shapeshifter error
    ---------------------------
    System.InvalidOperationException: Process has exited, so the requested information is not available.
       at System.Diagnostics.Process.EnsureState(State state)
       at System.Diagnostics.Process.get_MainWindowHandle()
       at System.Diagnostics.Process.CloseMainWindow()
       at Shapeshifter.WindowsDesktop.Services.ProcessManager.CloseProcess(Process process)
       at Shapeshifter.WindowsDesktop.Services.ProcessManager.Dispose()
       at Autofac.Core.Disposer.Dispose(Boolean disposing)
       at Autofac.Util.Disposable.Dispose()
       at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
       at Autofac.Util.Disposable.Dispose()
       at Autofac.Core.Container.Dispose(Boolean disposing)
       at Autofac.Util.Disposable.Dispose()
       at Shapeshifter.WindowsDesktop.App.OnExit(ExitEventArgs e)
       at System.Windows.Application.DoShutdown()
       at System.Windows.Application.ShutdownImpl()
       at System.Windows.Application.ShutdownCallback(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at Shapeshifter.WindowsDesktop.App.Main()
       at Shapeshifter.WindowsDesktop.Program.Main(String[] args)
    ---------------------------
    OK   
    ---------------------------

**Comment by ffMathy** [comment]
Solution: Don't you dare shut Shapeshifter down! :smile: 

I'll get it solved tomorrow.

**Comment by KoalaBear84** [comment]
:D

**Comment by ffMathy** [comment]
I think it happens only after opening processes with the `ProcessManager`. I couldn't replicate the issue consistently, although I have been having it once in a while.

Could you review #138 and see if you agree with the way it is fixed?

**Comment by KoalaBear84** [comment]
Looks like the issue was that CloseMainWindow was called when the process was already 'gone'.

If there are no race condition's, then it should work. Will only happen when the process is finally closed between context switch of the check and the CloseMainWindow call. Should be OK.
