### ISSUE TITLE
Make installer sign executable and install it to the trusted authorities list

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#38]
In order to allow Shapeshifter to copy and paste from processes that are running with administrative privileges, a trusted root certificate must be installed on the client machine with the installer.

**Comment by KoalaBear84** [comment]
Great find.

And you mentioned that it needs a certificate, which is expensive?

**Comment by ffMathy** [comment]
Yes. A certificate is very expensive ($1000 a year or so), but by making a certificate yourself, you can also get around it by installing that certificate as a "trusted certificate" on the target machine.

If the installer did this, it would also solve the problem. It is less clean, and we need to make sure it is uninstalled again when people want to remove Shapeshifter. But it will work.

**Comment by ffMathy** [comment]
This should be linked with https://github.com/ffMathy/Shapeshifter/issues/17.

**Comment by szepeviktor** [comment]
This one from Comodo costs $75/year

https://cheapsslsecurity.com/comodo/codesigningcertificate.html

**Comment by ffMathy** [comment]
Still, I prefer free, which it is if the installer installs a certificate itself.

**Comment by szepeviktor** [comment]
Certum provided it for free for open-source projects

https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

**Comment by ffMathy** [comment]
Alright, I am stuck again. The `develop` branch currently has the work so far on it. There is an `InstallArgumentProcessor` which attempts to launch itself as administrator, then copies itself to the Program Files folder, then installs a root certificate, and then attempts to sign the executable with that root certificate.

However, in this process, it throws an exception. Can anyone help?

**Comment by KoalaBear84** [comment]
Forgot to check in ISignHelper?

**Comment by ffMathy** [comment]
Oh my god. That's stupid. I'll do that when I get home.

**Comment by ffMathy** [comment]
I added them with 50bc768. Try again.

**Comment by KoalaBear84** [comment]
Do you mean this exception?

---------------------------
Shapeshifter error
---------------------------
System.Runtime.InteropServices.COMException (0x8009200B): Cannot find the certificate and private key for decryption. (Exception from HRESULT: 0x8009200B)

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)

   at Shapeshifter.WindowsDesktop.Native.Helpers.SignHelper.SignCode(IntPtr pSubjectInfo, IntPtr pSignerCert, IntPtr pSignatureInfo, IntPtr pProviderInfo) in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop.Native\Helpers\SignHelper.cs:line 238

   at Shapeshifter.WindowsDesktop.Native.Helpers.SignHelper.SignAssemblyWithCertificate(String assemblyPath, X509Certificate2 certificate) in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop.Native\Helpers\SignHelper.cs:line 113

   at Shapeshifter.WindowsDesktop.Services.Arguments.InstallArgumentProcessor.Install() in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop\Services\Arguments\InstallArgumentProcessor.cs:line 73

   at Shapeshifter.WindowsDesktop.Services.Arguments.InstallArgumentProcessor.Process() in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop\Services\Arguments\InstallArgumentProcessor.cs:line 58

   at Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor.ProcessArgumentsWithNoArgumentProcessor(INoArgumentProcessor processor) in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop\Services\Arguments\AggregateArgumentProcessor.cs:line 90

   at Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor.ProcessNoArgumentProcessors() in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop\Services\Arguments\AggregateArgumentProcessor.cs:line 79

   at Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor.ProcessArguments(String[] arguments) in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop\Services\Arguments\AggregateArgumentProcessor.cs:line 66

   at Shapeshifter.WindowsDesktop.Main.Start(String[] arguments) in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop\Main.cs:line 39

   at Shapeshifter.WindowsDesktop.App.OnStartup(StartupEventArgs e) in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop\App.xaml.cs:line 56

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at Shapeshifter.WindowsDesktop.App.Main() in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop\obj\Debug\App.g.cs:line 0

   at Shapeshifter.WindowsDesktop.Program.Main() in C:\Users\User\Source\Repos\Shapeshifter\src\Shapeshifter.WindowsDesktop\Program.cs:line 62
---------------------------
OK   
---------------------------

**Comment by ffMathy** [comment]
Yes, exactly. It happens when it tries to sign the executable with the self-signed certificate it created. I don't know much about signing, so I might be doing something wrong.

**Comment by ffMathy** [comment]
Maybe we could try signing the executable manually, getting that to work, and see if that produces a proper result, and then compare those certificates with the ones that Shapeshifter created.

**Comment by ffMathy** [comment]
The steps described (here)[http://blogs.techsmith.com/inside-techsmith/devcorner-debug-uiaccess/] is exactly what I am trying to do (just programmatically).

**Comment by ffMathy** [comment]
Hmmm it seems what I am doing is wrong. I am generating a CA certificate, which I then use to issue a code signing certificate. The Techsmith instructions above (which actually work) just have a CA certificate. That's very interesting.

I'll investigate more.

**Comment by ffMathy** [comment]
Holy shit, it works! Shapeshifter can now paste to administrator processors without being run as administrator itself!

Still need to refactor some code though.

**Comment by KoalaBear84** [comment]
That sir, is great news! :)

**Comment by dvitonis** [comment]
Great progress!
