### ISSUE TITLE
Captured Control + Arrow Keys upon boot

### ISSUE THREAD

**Issue by thegabrielstein** [ffMathy/Shapeshifter#443]
In v6.2018.507.2545, especially on first boot, it captures the Control and Arrow Keys and doesn't allow for Control + Right or Left arrows to navigate text word-by-word (vs letter-by-letter) when word processing. And it won't open the overlay when pressing Control + V. Not sure how to reproduce more than that. 

Seems like pressing Control + V clears the word processing error, but doesn't open the overlay for whatever reason. Closing the program from the tray and reopening seems to clear it.

**Comment by ffMathy** [comment]
Nice find. Quite critical too! Thanks!

**Comment by SmartManoj** [comment]
It takes time to close the program from the tray and reopen.Nice to have a feature like restart on tray icon

**Comment by ffMathy** [comment]
I think this might happen due to timing issues between when one believes Shapeshifter is ready, and when it actually is.

I made it now so that the tray icon only pops up if Shapeshifter is truly fully ready. So if you see the tray icon, you can count on it being available.

**Comment by thegabrielstein** [comment]
Hmm, seems like this is still happening as of 513.2683, the issue is present as long as the program is open, and even relaunching doesn't fix it now. 

Relaunching just now threw an error popup and crashed, and here's the log:

```2018-05-23 00:01:20.559 [#9812] [Shapeshifter.WindowsDesktop.Services.Files.FileManager] [VRB]
Deleting file C:\Users\test\AppData\Local\Temp\Shapeshifter\Shapeshifter20180522.log.

2018-05-23 00:01:43.828 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Window message hook was constructed using 5 interceptors.

2018-05-23 00:01:44.223 [#9812] [Shapeshifter.WindowsDesktop.Operations.Startup.ApplicationEntrypoint] [VRB]
Application entry point initialized.

2018-05-23 00:01:44.630 [#9812] [Shapeshifter.WindowsDesktop.Operations.Startup.StartupPreparationOperation] [VRB]
Invoking the startup preparation operation.

2018-05-23 00:01:44.663 [#9812] [Shapeshifter.WindowsDesktop.Services.Processes.ProcessManager] [VRB]
Closing all duplicate processes.

2018-05-23 00:01:47.629 [#9812] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [INF]
Processing given command line arguments [].

2018-05-23 00:01:47.730 [#9812] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [INF]
Running single argument processors.

2018-05-23 00:01:47.786 [#9812] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [INF]
Running no-argument processors since no single argument processor was used.

2018-05-23 00:01:47.786 [#9812] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [VRB]
Triggering no-argument processor DefaultArgumentProcessor.

2018-05-23 00:01:51.286 [#9812] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [VRB]
All command line arguments have been processed. Argument processor won't trigger termination.

2018-05-23 00:01:51.286 [#9812] [Shapeshifter.WindowsDesktop.Operations.Startup.StartupPreparationOperation] [VRB]
Startup preparation operation completed.

2018-05-23 00:01:51.288 [#9812] [Shapeshifter.WindowsDesktop.Operations.Startup.MainWindowPreparationOperation] [VRB]
Initializing clipboard quantity overlay and main window.

2018-05-23 00:01:53.132 [#9812] [Shapeshifter.WindowsDesktop.Operations.Startup.MainWindowPreparationOperation] [VRB]
The main window source handle has been determined.

2018-05-23 00:01:53.133 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed message hook.

2018-05-23 00:01:53.134 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor MouseWheelHook.

2018-05-23 00:01:53.447 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.Interceptors.AeroColorChangeInterceptor] [INF]
Aero color was changed to #FF6E6E6E.

2018-05-23 00:01:53.447 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor AeroColorChangeInterceptor.

2018-05-23 00:01:53.448 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor ClipboardCopyInterceptor.

2018-05-23 00:01:53.452 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor KeyInterceptor.

2018-05-23 00:01:53.625 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor PasteHotkeyInterceptor.

2018-05-23 00:01:54.037 [#9812] [Shapeshifter.WindowsDesktop.Mediators.ClipboardUserInterfaceInteractionMediator] [INF]
Installing clipboard hook.

2018-05-23 00:01:58.652 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_SHOWWINDOW to interceptor KeyInterceptor.

2018-05-23 14:44:21.829 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:44:21.879 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:54:49.276 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:54:49.278 [#9812] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:54:49.278 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:55:55.639 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:55:55.640 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:55:55.792 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:55:55.793 [#9812] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:55:55.793 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:55:55.942 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:55:55.943 [#9812] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:55:55.943 [#9812] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:56:27.985 [#12580] [Shapeshifter.WindowsDesktop.Services.Files.FileManager] [VRB]
Deleting file C:\Users\test\AppData\Local\Temp\Shapeshifter\Shapeshifter20180523.log.

2018-05-23 14:56:28.629 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Window message hook was constructed using 5 interceptors.

2018-05-23 14:56:28.674 [#12580] [Shapeshifter.WindowsDesktop.Operations.Startup.ApplicationEntrypoint] [VRB]
Application entry point initialized.

2018-05-23 14:56:28.680 [#12580] [Shapeshifter.WindowsDesktop.Operations.Startup.StartupPreparationOperation] [VRB]
Invoking the startup preparation operation.

2018-05-23 14:56:28.681 [#12580] [Shapeshifter.WindowsDesktop.Services.Processes.ProcessManager] [VRB]
Closing all duplicate processes.

2018-05-23 14:56:33.864 [#12580] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [INF]
Processing given command line arguments [].

2018-05-23 14:56:33.867 [#12580] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [INF]
Running single argument processors.

2018-05-23 14:56:33.897 [#12580] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [INF]
Running no-argument processors since no single argument processor was used.

2018-05-23 14:56:33.898 [#12580] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [VRB]
Triggering no-argument processor DefaultArgumentProcessor.

2018-05-23 14:56:34.111 [#12580] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [VRB]
All command line arguments have been processed. Argument processor won't trigger termination.

2018-05-23 14:56:34.111 [#12580] [Shapeshifter.WindowsDesktop.Operations.Startup.StartupPreparationOperation] [VRB]
Startup preparation operation completed.

2018-05-23 14:56:34.112 [#12580] [Shapeshifter.WindowsDesktop.Operations.Startup.MainWindowPreparationOperation] [VRB]
Initializing clipboard quantity overlay and main window.

2018-05-23 14:56:34.131 [#12580] [Shapeshifter.WindowsDesktop.Operations.Startup.MainWindowPreparationOperation] [VRB]
The main window source handle has been determined.

2018-05-23 14:56:34.132 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed message hook.

2018-05-23 14:56:34.133 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor MouseWheelHook.

2018-05-23 14:56:34.135 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.Interceptors.AeroColorChangeInterceptor] [INF]
Aero color was changed to #FF6E6E6E.

2018-05-23 14:56:34.135 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor AeroColorChangeInterceptor.

2018-05-23 14:56:34.136 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor ClipboardCopyInterceptor.

2018-05-23 14:56:34.138 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor KeyInterceptor.

2018-05-23 14:56:34.140 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor PasteHotkeyInterceptor.

2018-05-23 14:56:34.150 [#12580] [Shapeshifter.WindowsDesktop.Mediators.ClipboardUserInterfaceInteractionMediator] [INF]
Installing clipboard hook.

2018-05-23 14:56:34.451 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_SHOWWINDOW to interceptor KeyInterceptor.

2018-05-23 14:57:05.279 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:57:05.284 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:57:05.436 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:57:05.437 [#12580] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:57:05.437 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:57:05.656 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:57:05.657 [#12580] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:57:05.657 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:57:05.832 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:57:05.833 [#12580] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:57:05.833 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:57:05.957 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:57:05.958 [#12580] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:57:05.958 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:57:23.232 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:57:23.232 [#12580] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:57:23.232 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:57:23.346 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:57:23.347 [#12580] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:57:23.347 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:57:23.501 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:57:23.502 [#12580] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Cancelling duration mediator combination registration.

2018-05-23 14:57:23.502 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:57:40.332 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor KeyInterceptor.

2018-05-23 14:57:40.394 [#12580] [Shapeshifter.WindowsDesktop.Controls.Window.MainWindow] [INF]
Hiding user interface.

2018-05-23 14:57:40.442 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_HOTKEY to interceptor PasteHotkeyInterceptor.

2018-05-23 14:57:40.442 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_SHOWWINDOW to interceptor KeyInterceptor.

2018-05-23 14:57:40.444 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_CLIPBOARDUPDATE to interceptor ClipboardCopyInterceptor.

2018-05-23 14:57:40.525 [#12580] [] [ERR]
An unhandled error occured.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Shapeshifter.WindowsDesktop.Controls.Window.ViewModels.UserInterfaceViewModel.<RemoveCurrentElementAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Shapeshifter.WindowsDesktop.Controls.Window.ViewModels.UserInterfaceViewModel.<ClipboardUserInterfaceInteractionMediator_RemovedCurrentItem>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Shapeshifter.WindowsDesktop.Program.Main(String[] args)

2018-05-23 14:57:40.697 [#12580] [] [VRB]
Reporting the log entry "An unhandled error occured.".

2018-05-23 14:57:51.567 [#12580] [] [VRB]
Reported the log entry An unhandled error occured. as https://github.com/ffMathy/Shapeshifter/issues/476.

2018-05-23 14:57:51.748 [#12580] [Shapeshifter.WindowsDesktop.Services.Messages.Interceptors.ClipboardCopyInterceptor] [INF]
Clipboard update message skipped.

2018-05-23 14:58:35.908 [#14996] [Shapeshifter.WindowsDesktop.Services.Files.FileManager] [VRB]
Deleting file C:\Users\test\AppData\Local\Temp\Shapeshifter\Shapeshifter20180523.log.

2018-05-23 14:58:36.132 [#14996] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Window message hook was constructed using 5 interceptors.

2018-05-23 14:58:36.179 [#14996] [Shapeshifter.WindowsDesktop.Operations.Startup.ApplicationEntrypoint] [VRB]
Application entry point initialized.

2018-05-23 14:58:36.184 [#14996] [Shapeshifter.WindowsDesktop.Operations.Startup.StartupPreparationOperation] [VRB]
Invoking the startup preparation operation.

2018-05-23 14:58:36.185 [#14996] [Shapeshifter.WindowsDesktop.Services.Processes.ProcessManager] [VRB]
Closing all duplicate processes.

2018-05-23 14:58:38.472 [#14996] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [INF]
Processing given command line arguments [].

2018-05-23 14:58:38.474 [#14996] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [INF]
Running single argument processors.

2018-05-23 14:58:38.477 [#14996] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [INF]
Running no-argument processors since no single argument processor was used.

2018-05-23 14:58:38.478 [#14996] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [VRB]
Triggering no-argument processor DefaultArgumentProcessor.

2018-05-23 14:58:38.676 [#14996] [Shapeshifter.WindowsDesktop.Services.Arguments.AggregateArgumentProcessor] [VRB]
All command line arguments have been processed. Argument processor won't trigger termination.

2018-05-23 14:58:38.676 [#14996] [Shapeshifter.WindowsDesktop.Operations.Startup.StartupPreparationOperation] [VRB]
Startup preparation operation completed.

2018-05-23 14:58:38.677 [#14996] [Shapeshifter.WindowsDesktop.Operations.Startup.MainWindowPreparationOperation] [VRB]
Initializing clipboard quantity overlay and main window.

2018-05-23 14:58:38.695 [#14996] [Shapeshifter.WindowsDesktop.Operations.Startup.MainWindowPreparationOperation] [VRB]
The main window source handle has been determined.

2018-05-23 14:58:38.696 [#14996] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed message hook.

2018-05-23 14:58:38.697 [#14996] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor MouseWheelHook.

2018-05-23 14:58:38.700 [#14996] [Shapeshifter.WindowsDesktop.Services.Messages.Interceptors.AeroColorChangeInterceptor] [INF]
Aero color was changed to #FF6E6E6E.

2018-05-23 14:58:38.700 [#14996] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor AeroColorChangeInterceptor.

2018-05-23 14:58:38.701 [#14996] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor ClipboardCopyInterceptor.

2018-05-23 14:58:38.704 [#14996] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor KeyInterceptor.

2018-05-23 14:58:38.707 [#14996] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Installed interceptor PasteHotkeyInterceptor.

2018-05-23 14:58:38.717 [#14996] [Shapeshifter.WindowsDesktop.Mediators.ClipboardUserInterfaceInteractionMediator] [INF]
Installing clipboard hook.

2018-05-23 14:58:38.805 [#14996] [Shapeshifter.WindowsDesktop.Services.Messages.WindowMessageHook] [INF]
Passing message WM_SHOWWINDOW to interceptor KeyInterceptor.

2018-05-23 14:58:47.510 [#14996] [Shapeshifter.WindowsDesktop.Services.Processes.ProcessManager] [VRB]
Launching explorer under verb null in  with arguments "C:\Users\test\AppData\Local\Temp\Shapeshifter".```

**Comment by ffMathy** [comment]
According to the logs, the error that happened caused the clipboard lock. If Shapeshifter crashes when the UI is active like what happened here, it won't be able to disable its keyboard hooks properly.

I'll fix the error.

Did you happen to be deleting items really fast when this happened?

It seems as if this issue should already have been fixed. What version was this on?

**Comment by thegabrielstein** [comment]
Hmm, yeah that makes sense. Build was 2018.513.2683. Should say in the logs though, right #539? 

And I wasn't deleting items quickly. But have in the past, did that cause a persistent bug to result though?

**Comment by ffMathy** [comment]
In that case it makes sense. The error should already be resolved. That right there is not the latest prerelease but a stable release and is very old. 

The latest prerelease is ironically more stable right now actually, but of course it's a risk. 

From that build number I can tell it was compiled the 13th of May. Try the latest prerelease that was compiled yesterday. 

Just note that once you open a prerelease version, it will also auto update to prereleases and it will keep doing so even if you install a non prerelease version in the future.
